### ISSUE TITLE
Problem when submiting cart (POST /sale)

### ISSUE THREAD

**Issue by ludovicm67** [AIUS/AIUS_Caisse#1]
Always get the following error when submitting a cart : 

`{status: "error", message: "Already id of product."}`

**Comment by ludovicm67** [comment]
Exemple de requête donnant l'erreur :

```json
{
	"data": [
		{
			"id": 1,
			"quantity": 2
		},
		{
			"id": 2,
			"quantity": 5
		},
		{
			"id": 3,
			"quantity": 3
		}
	],
	"token": "00000000-0000-0000-0000-000000000000"
}
```

Mais avec un seul item, ça fonctionne nickel.

**Comment by Lukc** [comment]
@mickaelB67, des nouvelles ?

@ludovicm67, y’a pas mal de toilettage en attente sur le code de Mika. Désolé si la résolution de ton problème prend un peu de temps ; je suis juste occupé sur d’autres choses. :(

**Comment by Izimic** [comment]
Bug Fix

**Comment by Lukc** [comment]
Corrigé en 8d215e3204af8350badaed4502ec8f91a3178ba6.
